import type { editor } from 'monaco-editor'

export const monacoThemeLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '9699a3', fontStyle: 'italic' },
    { token: 'keyword', foreground: '9d7cd8' },
    { token: 'string', foreground: '587539' },
    { token: 'number', foreground: 'b15c00' },
    { token: 'regexp', foreground: '587539' },
    { token: 'type', foreground: '007197' },
    { token: 'class', foreground: '007197' },
    { token: 'function', foreground: '34548a' },
    { token: 'variable', foreground: '3760bf' },
    { token: 'constant', foreground: 'b15c00' },
    { token: 'property', foreground: '3760bf' },
    { token: 'operator', foreground: '9d7cd8' },
    { token: 'tag', foreground: '8c4351' },
    { token: 'attribute.name', foreground: 'b15c00' },
    { token: 'attribute.value', foreground: '587539' },
  ],
  colors: {
    // 'editor.background': '#d5d6db',
    'editor.foreground': '#3760bf',
    'editor.lineHighlightBackground': '#e9e9ed',
    'editor.selectionBackground': '#b3d3ff',
    'editor.inactiveSelectionBackground': '#d7e3f4',
    'editorLineNumber.foreground': '#a1a6c5',
    'editorLineNumber.activeForeground': '#3760bf',
    'editorCursor.foreground': '#3760bf',
    'editorWhitespace.foreground': '#b8bcd0',
    'editorIndentGuide.background': '#c7c9d1',
    'editorIndentGuide.activeBackground': '#a1a6c5',
  },
}

export const monacoThemeDark: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'bb9af7' },
    { token: 'string', foreground: '9ece6a' },
    { token: 'number', foreground: 'ff9e64' },
    { token: 'regexp', foreground: '9ece6a' },
    { token: 'type', foreground: '2ac3de' },
    { token: 'class', foreground: '2ac3de' },
    { token: 'function', foreground: '7aa2f7' },
    { token: 'variable', foreground: 'c0caf5' },
    { token: 'constant', foreground: 'ff9e64' },
    { token: 'property', foreground: '7dcfff' },
    { token: 'operator', foreground: '89ddff' },
    { token: 'tag', foreground: 'f7768e' },
    { token: 'attribute.name', foreground: 'e0af68' },
    { token: 'attribute.value', foreground: '9ece6a' },
  ],
  colors: {
    'editor.background': '#17181c',
    'editor.foreground': '#c0caf5',
    'editor.lineHighlightBackground': '#292e42',
    'editor.selectionBackground': '#283457',
    'editor.inactiveSelectionBackground': '#28345780',
    'editorLineNumber.foreground': '#3b4261',
    'editorLineNumber.activeForeground': '#9aa5ce',
    'editorCursor.foreground': '#c0caf5',
    'editorWhitespace.foreground': '#3b4261',
    'editorIndentGuide.background': '#2f334d',
    'editorIndentGuide.activeBackground': '#565f89',
  },
}

export const xtermLightTheme = {
  background: '#ffffff',
  foreground: '#24292e',
  cursor: '#24292e',
  cursorAccent: '#ffffff',
  selectionBackground: '#c8e1ff',
  selectionForeground: '#24292e',
  black: '#24292e',
  red: '#d73a49',
  green: '#22863a',
  yellow: '#b08800',
  blue: '#0366d6',
  magenta: '#6f42c1',
  cyan: '#1b7c83',
  white: '#6a737d',
  brightBlack: '#959da5',
  brightRed: '#cb2431',
  brightGreen: '#22863a',
  brightYellow: '#dbab09',
  brightBlue: '#005cc5',
  brightMagenta: '#5a32a3',
  brightCyan: '#3192aa',
  brightWhite: '#d1d5da',
}

export const xtermDarkTheme = {
  background: 'oklch(0.21 0.0075 275)',
  foreground: '#e6edf3',
  cursor: '#e6edf3',
  cursorAccent: '#0d1117',
  selectionBackground: '#1f6feb4d',
  selectionForeground: '#e6edf3',
  black: '#484f58',
  red: '#ff7b72',
  green: '#7ee787',
  yellow: '#ffa657',
  blue: '#79c0ff',
  magenta: '#d2a8ff',
  cyan: '#a5d6ff',
  white: '#e6edf3',
  brightBlack: '#6e7681',
  brightRed: '#ffa198',
  brightGreen: '#56d364',
  brightYellow: '#ffb757',
  brightBlue: '#a5d6ff',
  brightMagenta: '#d2a8ff',
  brightCyan: '#b3d8ff',
  brightWhite: '#f0f6fc',
}
